version: "3"
services:

    php:
        image: php:8.2-fpm
        container_name: php
        networks:
            backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/home/blog-api
            - ./public:/home/blog-api/public

    nginx:
        image: nginx:latest
        restart: always
        container_name: nginx
        networks:
            backend:
        ports:
            - "80:80"
        volumes:
            - ./:/home/blog-api
            - ./public:/home/blog-api/public
            - ./nginx.conf:/etc/nginx/nginx.conf

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        env_file: .env
        networks:
            backend:
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./mysql:/var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --character-set-client-handshake=FALSE

    redis:
        image: redis:latest
        container_name: redis
        networks:
            backend:
        command: redis-server --port 13000
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - "13000:13000"

networks:
    backend:
